const ACTION_TYPES = {
  FETCH_MENU_DETAILS: "FETCH_MENU_DETAILS",
  FETCH_MENU_DETAILS_IS_SUCCESS: "FETCH_MENU_DETAILS_IS_SUCCESS",
  FETCH_MENU_DETAILS_IS_FAILURE:"FETCH_MENU_DETAILS_IS_FAILURE",
  UPDATE_CART: "UPDATE_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  LOGIN_SUCCSS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",
  GET_ORDERS: "GET_ORDERS",
  GET_ALL_ORDERS: "GET_ALL_ORDERS",
  SUBMIT_ORDER: "SUBMIT_ORDER",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  FETCH_ORDER_STATUS: "FETCH_ORDER_STATUS",
  FETCH_ORDER_STATUS_SUCCESS: "FETCH_ORDER_STATUS_SUCCESS",
  FETCH_ORDER_STATUS_FAILURE: "FETCH_ORDER_STATUS_FAILURE"
};

export default ACTION_TYPES;
