
const ACTION_TYPES = {
    FETCH_MENU_DETAILS: 'FETCH_MENU_DETAILS',
    FETCH_MENU_DETAILS_IS_SUCCESS: 'FETCH_MENU_DETAILS_IS_SUCCESS',
    UPDATE_CART: 'UPDATE_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART'
}

export default ACTION_TYPES;