const ACTION_TYPES = {
  FETCH_MENU_DETAILS: "FETCH_MENU_DETAILS",
  FETCH_MENU_DETAILS_IS_SUCCESS: "FETCH_MENU_DETAILS_IS_SUCCESS",
  UPDATE_CART: "UPDATE_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  LOGIN_SUCCSS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  GET_ORDERS: "GET_ORDERS",
};

export default ACTION_TYPES;
